version: '3'
services:
  web:
    depends_on:
      - "app"
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  app:
    build: .
    depends_on:
      - "mysql"
      - "redis"
    environment:
      - "DB_USER=root"
      - "DB_PASSWORD=password1!"
      - "DB_HOST=mysql"
      - "DB_NAME=mysqldb"
      - "REDIS_ENDPOINT=redis:6379"
  mysql:
    image: mysql:5.7
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: "password1!"
      MYSQL_DATABASE: mysqldb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
  redis:
    image: redis

volumes:
  mysql-data:
    external:
      name: mysql-volume
